all: Group7_UDPServer Group7_UDPClient
Group7_UDPServer: Group7_UDPServer.c
	gcc Group7_UDPServer.c -o Group7_UDPServer
Group7_UDPClient: Group7_UDPClient.c
	gcc Group7_UDPClient.c -o Group7_UDPClient
clean:
	rm Group7_UDPServer Group7_UDPClient
